import { createContext, useContext } from 'react'

interface LanguageContextType {
  language: 'en' | 'ar'
  toggleLanguage: () => void
  translations: typeof translations.en
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Helper function to get initial language from localStorage or default to 'en'
export const getInitialLanguage = (): 'en' | 'ar' => {
  if (typeof window !== 'undefined') {
    const savedLanguage = localStorage.getItem('itida-language')
    if (savedLanguage === 'en' || savedLanguage === 'ar') {
      return savedLanguage
    }
  }
  return 'en'
}

// Helper function to save language to localStorage
export const saveLanguageToStorage = (language: 'en' | 'ar'): void => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('itida-language', language)
  }
}

export const translations = {
  en: {
    // Header
    home: 'Home',
    benefits: 'Benefits',
    contact: 'Contact',
    callUs: 'Call: 16248',

    // Hero additional
    companies: 'Companies',
    licenses: 'Licenses',
    partners: 'Partners',

    // LoginForm additional
    accessAccountDesc: 'Access your ITIDA account and manage your ICT activities',
    enterUsernameEmail: 'Enter your username or email',
    enterPassword: 'Enter your password',
    recoverNow: 'Recover Now',

    // Services additional
    itidaServices: 'Itida Services',
    services: 'Services',

    // Footer additional
    footerDesc: "Empowering Egypt's digital transformation through comprehensive ICT sector regulation, innovation support, and ecosystem development.",
    quickLinks: 'Quick Links',
    aboutItida: 'About ITIDA',
    trainingPrograms: 'Training Programs',
    copyright: '© 2024 ITIDA. All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    contactLabel: 'Contact:',
    emailLabel: 'Email:',
    addressLabel: 'Address (as shown in the commercial register or tax card)',
    addressText: 'Smart Village, Cairo-Alexandria Desert Road, Giza, Egypt',

    // Registration Sidebar
    registrationCompany: 'Registration Company',
    companyHeadContacts: 'Company\'s Head & Contacts',
    financialInformation: 'Financial & Market Information',

    // Hero
    heroTitle: 'Join Egypt\'s Official ICT Sector Registry',
    heroSubtitle: 'Empowering Digital Innovation and Growth',
    heroDescription: 'The Information Technology Industry Development Agency (ITIDA) is the central governmental authority regulating Egypt\'s Information and Communications Technology (ICT) sector.',
    learnMore: 'Learn More',

    // Login Form
    alreadyMember: 'Already ITIDA Member',
    usernameEmail: 'Username or Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    login: 'Sign In',
    forgotPassword: 'Lost your password?',
    joinNow: 'Join ITIDA Now',
    dontHaveAccount: 'Don\'t have an account?',
    registerHere: 'Register here',
    username: 'UserName/Email',
    crn: 'CRN',
    licenseNo: 'License No.',

    // User Roles
    userRole: 'User Role',
    individual: 'Individual',
    company: 'Company',
    government: 'Government',

    // Features
    featuresTitle: 'Why Choose ITIDA?',
    licensing: 'Licensing',
    licensingDesc: 'Official licenses for ICT activities',
    innovation: 'Innovation Support',
    innovationDesc: 'Foster digital innovation',
    ecosystem: 'Digital Ecosystem',
    ecosystemDesc: 'Thriving ICT community',
    secureAccess: 'Secure Access Portal',
    secureAccessDesc: 'Access your ITIDA dashboard with enterprise-grade security',
    recoverYourAccount: 'Recover Your Account',
    recoverYourAccountDesc: 'Easily recover access to your ITIDA account with our secure recovery process',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorAuthDesc: 'Enhanced security for your account',
    encryptedComm: 'Encrypted Communication',
    encryptedCommDesc: 'All data is encrypted in transit',
    realTimeMonitoring: 'Real-time Monitoring',
    realTimeMonitoringDesc: 'Track your activities and licenses',

    // Features Additional
    comprehensiveIctSolutions: 'Comprehensive ICT Solutions',
    comprehensiveIctSolutionsDesc: 'From licensing and regulation to innovation support and ecosystem development, ITIDA provides end-to-end solutions for Egypt\'s digital transformation journey.',
    governmentBackedAuthority: 'Government-backed authority',
    internationalStandardsCompliance: 'International standards compliance',
    support24x7: '24/7 support and assistance',
    exploreAllServices: 'Explore All Services',
    discoverBenefits: 'Discover the comprehensive benefits and services that make ITIDA the leading authority in Egypt\'s ICT sector development',
    backToHome: 'Back to Home',

    // Footer
    poweredBy: 'Proudly powered by ITIDA',
    itidaDb: 'ITIDA DB',

    // Forgot Password
    forgotPasswordTitle: 'Forgot Password?',
    forgotPasswordSubtitle: 'Enter your email address and we\'ll send you a link to reset your password.',
    emailAddress: 'Email Address',
    enterEmail: 'Enter your email',
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    checkYourEmail: 'Check Your Email',
    resetInstructions: 'We\'ve sent a password reset link to {email}. Please check your email and click the link to reset your password.',
    backToLogin: 'Back to Login',
    sendAnotherEmail: 'Send Another Email',
    didntReceiveEmail: 'Didn\'t receive the email? Check your spam folder or contact support.',
    needHelp: 'Need help?',
    contactSupport: 'Contact Support',
    helpCenter: 'Help Center',
    pleaseEnterEmail: 'Please enter your email address',
    pleaseEnterValidEmail: 'Please enter a valid email address',
    somethingWentWrong: 'Something went wrong. Please try again.',

    // Registration Page
    companiesRegistrationForm: 'Companies Registration Form',
    completeCompanyRegistration: 'Complete your company registration with ITIDA',
    companyLegalInformation: 'Company Legal Information',
    contactInformation: 'Contact Information',
    activitiesAttachments: 'Activities & Attachments',
    previous: 'Previous',
    next: 'Next',
    submitRegistration: 'Submit Registration',
    companyOverView: 'Company Overview',
    companyOverviewPlaceholder: 'Briefly describe your company\'s background, core competencies, and key achievements.',

    // Tab 1: Company Legal Information
    companyLegalInfoTitle: 'Company Legal Information',
    companyLegalInfoSubtitle: '(As mentioned in the commercial register or tax card)',
    companyNameEnglish: 'Company Name English',
    companyNameArabic: 'Company Name Arabic',
    commercialDenomination: 'Commercial Denomination',
    legalType: 'Legal Type',
    selectLegalType: 'Select Legal Type',
    soleProprietorship: 'Sole Proprietorship',
    partnership: 'Partnership',
    limitedLiabilityCompany: 'Limited Liability Company',
    jointStockCompany: 'Joint Stock Company',
    branch: 'Branch',
    other: 'Other',
    registerUsing: 'Register Using',
    commercialRegistryNumber: 'Commercial Registry Number',
    unifiedCommercialRegistryNumber: 'Unified Commercial Registry Number',
    taxRegistryNumber: 'Tax Registry Number',
    commercialRegistrationDate: 'Commercial Registration Date',
    noteRegistrationOptions: 'Note: At least one registration option must be selected',
    officialCompanyEmail: 'Official Company\'s Email',
    yearOfEstablishment: 'Year of Establishment',
    selectYear: 'Select year',
    companyClassification: 'Company classification',
    crOffice: 'CR Office',
    classCode: 'Class Code',
    classCodeArabic: 'كود الفئة',
    mainBranch: 'محل رئيسى',
    otherMain: 'رئيسى آخر',
    branchOffice: 'محل فرعى',
    branchOther: 'فرعى',
    generalCenter: 'مركز عام',

    // Validation Messages
    thisFieldIsRequired: 'This field is required',
    onlyEnglishLettersAllowed: 'Only English letters are allowed',
    onlyArabicLettersAllowed: 'Only Arabic letters are allowed',
    invalidEmailAddress: 'Invalid email address',
    atLeastOneCompanyClassificationRequired: 'At least one company classification is required',
    atLeastOneRegistrationMethodSelected: 'At least one registration method must be selected',
    commercialRegistryNumberRequired: 'Commercial Registry Number is required',
    unifiedCommercialRegistryNumberRequired: 'Unified Commercial Registry Number is required',
    taxRegistryNumberRequired: 'Tax Registry Number is required',

    // Alert Messages
    alertTitle: 'Validation Error',
    alertTitleSuccess: 'Success',
    alertTitleWarning: 'Warning',
    alertTitleError: 'Error',
    pleaseCompleteAllRequiredFields: 'Please complete all required fields before proceeding',
    pleaseCompleteEmptyFields: 'Please complete the following empty fields:',
    formSubmissionBlocked: 'Form submission is blocked due to incomplete required fields',
    pleaseFillRequiredInformation: 'Please fill in all required information to continue',
    missingRequiredData: 'Missing required data',
    incompleteFormData: 'Incomplete form data',
    validationFailed: 'Validation failed',
    pleaseCheckFormData: 'Please check your form data and try again',
    requiredFieldsEmpty: 'Some required fields are empty',
    pleaseCompleteForm: 'Please complete the form before submitting',
    dataValidationError: 'Data validation error',
    formNotComplete: 'Form is not complete',
    pleaseReviewForm: 'Please review and complete the form',

    // Company Classification Options
    technology: 'Technology',
    consulting: 'Consulting',
    manufacturing: 'Manufacturing',
    retail: 'Retail',
    finance: 'Finance',
    healthcare: 'Healthcare',
    education: 'Education',

    // Class Code Options
    selectClassCode: 'Select Class Code',

    // Legal Type Options
    legalTypeSole: 'Sole proprietorship Co - شركة شخص واحد',
    legalTypeSoleCorporation: 'Sole Corporation - فردي',
    legalTypeGeneralPartnership: 'General Partnership - شركات مساهمة',
    legalTypeLimitedLiability: 'Limited Liability Company - ذات مسئولية محدودة',
    legalTypeJoint: 'Joint - شركة تضامن',
    legalTypeSpecialLimited: 'Special Limited Partnership – توصية بسيطة',
    legalTypeInherited: 'Inherited Company - واقع موروثة',
    legalTypeLimitedShares: 'Limited Partnership by Shares - توصية بالاسهم',
    legalTypeCooperative: 'Cooperative Associations - جمعيات تعاونية',
    legalTypeDeFacto: 'De Facto Company - شركه واقع',
    legalTypeBranchForeign: 'Branch of Foreign Company - فرع شركه اجنبيه',
    legalTypeNonProfit: 'Non-Profit Entities - جهات غير هادفة',

    // Tab 2: Contact Information
    contactInfoTitle: 'Contact Information',
    contactInfoSubtitle: 'Contact Information & Company Representative',
    companyAddress: 'Company Address',
    governorate: 'Governorate',
    selectGovernorate: 'Select Governorate',
    districtCity: 'District - City',
    streetAddress: 'Street Address',
    companyContactInfo: 'Company Contact Information',
    companyWebsiteUrl: 'Company Website URL',
    officialEmail: 'Official Email',
    phoneMobile: 'Phone/Mobile',
    companyHasBranches: 'Yes, Company Has Branches',
    companyRepresentative: 'Company In-charge / Representative',
    representativeSubtitle: '(As shown in the commercial register or power of attorney)',
    name: 'Name',
    title: 'Title',
    mobile: 'Mobile',
    nationalId: 'National ID',
    email: 'E-mail',
    requestApplicant: 'Request Applicant',
    companyInCharge: 'Company In-charge (as shown in commercial register or power of attorney)',
    representative: 'Representative',
    noteRequiredFields: 'Note: All required fields must be filled before proceeding to the next step',
    dateIsRequired: 'Date is required',
    invalidFormatUseMMYYYY: 'Invalid format. Use MM/YYYY',
    yearMustBeAtLeast15YearsAgo: 'Year must be at least 15 years ago (before {year})',
    companyHead: 'Company\'s Head',
    nidIssuedFrom: 'NID Issued from',
    egCairo: 'e.g., Cairo',
    nidIssueDate: 'NID Issue Date',
    mmYYYY: 'MM/YYYY',
    representativeInformations: 'Representative Informations',
    nationalIdRequired: 'National ID is required',
    nationalId14Digits: 'National ID must be exactly 14 digits',
    dateRangeError: 'Date must be between {minDate} and today',
    exampleGovernorate: 'e.g., Cairo',
    dateFormat: 'MM/YYYY',

    // Job Titles
    jobTitleResponsibleManager: 'Responsible Manager',
    jobTitlePartner: 'Partner',
    jobTitleManagerAndPartner: 'Manager and Partner',

    // Governorates
    cairo: 'Cairo',
    giza: 'Giza',
    alexandria: 'Alexandria',
    sharqia: 'Sharqia',
    gharbia: 'Gharbia',
    menoufia: 'Menoufia',
    qalyubia: 'Qalyubia',
    portSaid: 'Port Said',
    suez: 'Suez',
    ismailia: 'Ismailia',
    kafrElSheikh: 'Kafr El Sheikh',
    beheira: 'Beheira',
    assiut: 'Assiut',
    sohag: 'Sohag',
    qena: 'Qena',
    luxor: 'Luxor',
    aswan: 'Aswan',
    redSea: 'Red Sea',
    newValley: 'New Valley',
    matruh: 'Matruh',
    northSinai: 'North Sinai',
    southSinai: 'South Sinai',
    beniSuef: 'Beni Suef',
    fayoum: 'Fayoum',
    minya: 'Minya',
    dakahlia: 'Dakahlia',
    damietta: 'Damietta',
    otherGovernorate: 'Other',

    // Tab 3: Company Branches
    companyBranchesTitle: 'Company Branches',
    companyBranchesSubtitle: 'Manage company branches information',
    hasBranches: 'Company Has Branches',
    branchName: 'Branch Name',
    branchLocation: 'Branch Location',
    branchCountry: 'Branch Country',
    branchGovernorate: 'Branch Governorate',
    branchCity: 'Branch City',
    branchDistrict: 'Branch District',
    branchEmail: 'Branch Email',
    enterBranchName: 'Enter branch name',
    enterBranchLocation: 'Enter branch location',
    enterBranchCountry: 'Enter branch country',
    enterBranchGovernorate: 'Enter branch governorate',
    enterBranchCity: 'Enter branch city',
    enterBranchDistrict: 'Enter branch district',
    enterBranchEmail: 'Enter branch email',
    addBranchInfo: 'Add your company branches information here.',
    branchNumber: 'Branch',
    removeBranch: 'Remove Branch',
    addBranch: 'Add Branch',

    // Tab 4: Activities & Attachments
    activitiesAttachmentsTitle: 'Activities & Attachments',
    activitiesAttachmentsSubtitle: 'Select required activities and attach required documents',
    activitiesRequiredForLicensing: 'Activities Required for Licensing',
    softwareDesignServices: 'Software design, production, and development services',
    itSystemsServices: 'Information technology systems design, development, production, supply, and operation services',
    trustServices: 'Trust and electronic signature services',
    websitesPlatformsServices: 'Website, platform, and electronic transaction services using the internet',
    electronicsEmbeddedServices: 'Electronics and embedded systems design, development, and production services in the field of information and communication technology',
    contentDigitizationServices: 'Traditional content digitization services using information technology',
    callCenterBusinessServices: 'Call center and business process management services using information and communication technology',
    consultingResearchServices: 'Consulting, research and development, and entrepreneurship services in the field of information and communication technology',
    trainingLearningServices: 'Training and learning services in the field of information and communication technology',
    attachments: 'Attachments',
    attachmentsNote: 'Note: Only Images & PDF are accepted with max 3 MB',
    commercialRegisterImage: 'Commercial Register Image or Declaration Decision',
    taxCardImage: 'Tax Card Image',
    nationalIdImage: 'ID Image (National ID) for Responsible Manager',
    investmentGazetteImage: 'Investment Gazette or Company Contract Image',
    declarationUndertakingImage: 'Declaration and Undertaking Regarding IT Activities',
    representativeAuthorizationImage: 'Representative Authorization File',
    representativeNationalIdImage: 'Representative National ID',
    licenseReceipt: 'License Receipt',
    methodOfLicenseReceipt: 'Method of License Receipt',
    selectReceiptMethod: 'Select Receipt Method',
    postalMail: 'Postal Mail',
    personalPickup: 'Personal Pickup',
    courier: 'Courier',
    declarationAgreement: 'Declaration & Agreement',
    declarationText: 'I declare and undertake the accuracy of the submitted documents and my commitment to the relevant Egyptian laws, including those concerning electronic signatures, intellectual property rights, personal data protection, and cybercrime. I also undertake to practice licensed activities safely, ethically, responsibly, and transparently.',
    iAgree: 'I agree',
    noteDeclarationAgreement: 'Note: Declaration agreement must be accepted before submitting the request',

    // Additional Benefits
    additionalBenefitsTitle: 'Regulation of Information Technology Activity Licenses',
    additionalBenefitsDesc: 'The Information Technology Industry Development Agency (ITIDA) issues licenses for practicing specialized activities within the information and communication technology sector to regulate the IT sector and encourage investment in this vital field. This initiative aims to support market growth and foster a vibrant digital business environment.',
    activitiesEligible: 'Activities Eligible for Licensing:',
    eligibleActivities: [
      'Software design, production, and development services.',
      'Information technology systems design, development, production, supply, and operation services.',
      'Website, platform, and e-transaction services utilizing the internet.',
      'Electronics and embedded systems design and development, and electronics manufacturing in the ICT field.',
      'Traditional content digitization services using information technology.',
      'Call center and business process management services using information and communication technology.',
      'Consultancy, research and development, and entrepreneurship services in information and communication technology.',
      'Training and education services in information and communication technology.'
    ],
    city: 'City',
    district: 'District',
    street: 'Street',
    position: 'Position',
    email2: 'Email 2',
    companyHeadTitle: 'Company\'s Head',
    submit: 'Submit',
    namePlaceholder: 'Your name',
    positionPlaceholder: 'Position',
    mobilePhone: 'Mobile Phone',
    mobilePlaceholder: 'Mobile number',
    nationalIdPlaceholder: 'National ID',
    emailPlaceholder: 'Email',
    email2Placeholder: 'Email 2',
    websitePlaceholder: 'Website/social media platform (linkin,instgram,..)',

    // Financial Information - Missing translations
    chooseFile: 'Choose File',
    noFileChosen: 'No file chosen',
    paidCapital: 'Paid Capital',
    enterPaidCapital: 'Enter Paid capital',
    companySubClassification: 'Company\'s Sub Classification',
    industrySectors: 'Industry Sectors',
    selected100PercentEgyptian: 'selected (100% Egyptian)',
    enterDomesticSalesYear: 'Enter domestic sales Year',
    enterDomesticSalesValue: 'Enter domestic sales value',
    enterTotalRevenueYear: 'Enter total revenue year',
    enterAnnualRevenue: 'Enter annual revenue',
    enterTotalNumberOfEmployees: 'Enter total number of employees',
    selectCompanySize: 'Select company size',
    selectKeyTechnologies: 'Select Key Technologies',
    enterCustomKeyTechnology: 'Enter custom key technology',
    selectAffiliations: 'Select Affiliations',
    enterCustomAffiliation: 'Enter custom affiliation',
    selectMemberships: 'Select Memberships',
    enterCustomMembership: 'Enter custom membership',
    selectCertificates: 'Select Certificates',
    enterCustomCertificate: 'Enter custom certificate',
    selectPartnerships: 'Select Partnerships',
    enterCustomPartnership: 'Enter custom partnership',
    products: 'Products',
    productName: 'Product Name',
    productDescription: 'Product Description',
    services: 'Services',
    serviceName: 'Service Name',
    serviceDescription: 'Service Description',
    customerReference: 'Customer Reference',
    customerName: 'Customer Name',
    selectCountry: 'Select Country',
    projectSize: 'Project Size',
    scope: 'Scope',
    industriesSector: 'Industries Sector',
    projectDescription: 'Project Description',
    companyClassifications: 'Company Classifications',
    selectCompanyClassification: 'Select Company Classification',
    selectSubClassification: 'Select Sub Classification',
    selectIndustrySector: 'Select Industry Sector',
    year: 'Year',
    marketRegion: 'Market region',
    country: 'Country',
    typesProductsServicesExported: 'Types products / Services Exported',
    totalAmountExportsYearUSD: 'Total amount of exports / Year in USD',
    percentageOfEgyptianOwnership: 'Percentage Of Egyptian OwnerShip',
    percentageOfNonEgyptianOwnership: 'Percentage Of NonEgyptian OwnerShip',
    selectNationality: 'Select nationality',
    yes: 'Yes',
    no: 'No',
    exportInformation: 'Export Information',
    smallEmployees: 'Small (1-10 employees)',
    mediumEmployees: 'Medium (11-50 employees)',
    largeEmployees: 'Large (51-200 employees)',
    enterpriseEmployees: 'Enterprise (200+ employees)',
    selectCountryPlaceholder: 'Select Country',
    itidaLogoAlt: 'ITIDA Logo',
    englishFlagAlt: 'English',
    arabicFlagAlt: 'Arabic',
    switchToArabic: 'Switch to Arabic',
    switchToEnglish: 'Switch to English',

    // Financial Information - Additional missing translations
    auditedBalanceSheet: 'Audited Balance Sheet/P&L/Tax return + Certificate of Chartered Accountant',
    domesticSalesDetails: 'Domestic Sales Details',
    domesticSalesYear: 'Domestic Sales Year',
    domesticSalesValue: 'Domestic Sales Value',
    totalRevenueYear: 'Total Revenue Year',
    annualRevenue: 'Annual Revenue',
    totalNoOfEmployees: 'Total No of Employees',
    companySize: 'Company Size',
    keyTechnologies: 'Key Technologies',
    affiliation: 'Affiliation',
    memberships: 'Memberships',
    certificates: 'Certificates',
    partnerships: 'Partnerships',
    products: 'Products',
    services: 'Services',
    customerReference: 'Customer Reference',
    companyClassifications: 'Company Classifications',
    exportInformation: 'Export Information',
    marketRegion: 'Market (Region)',
    typesProductsServicesExported: 'Types products / Services Exported',
    totalAmountExportsYearUSD: 'Total amount of exports / Year in USD',
    percentageOfEgyptianOwnership: 'Percentage Of Egyptian OwnerShip',
    percentageOfNonEgyptianOwnership: 'Percentage Of NonEgyptian OwnerShip',
    partnersOrShareholdersNationalities: 'Partners Or Shareholders Nationalities',
    companyHasBranches: 'Company Has Branches',
    export: 'Export',
    import: 'Import',
    ownership: 'Ownership',
    nationality: 'Nationality',
    others: 'Others',
    manufacturing: 'Manufacturing',
    retail: 'Retail',
    consulting: 'Consulting',
    technology: 'Technology',
    finance: 'Finance',
    healthcare: 'Healthcare',
    education: 'Education',
    government: 'Government',
    nonProfit: 'Non-Profit',
    other: 'Other',
    production: 'Production',
    assembly: 'Assembly',
    outsourcing: 'Outsourcing',
    ecommerce: 'E-commerce',
    physicalStores: 'Physical Stores',
    b2b: 'B2B',
    b2c: 'B2C',
    it: 'IT',
    doYouExport: 'Do You Export',
    marketInformation: 'Market Information',
    softwareDevelopment: 'Software Development',
    hardware: 'Hardware',

    // Technology Companies
    ibm: 'IBM',
    microsoft: 'Microsoft',
    oracle: 'Oracle',
    sun: 'SUN',
    java: 'Java',
    openSource: 'Open Source',
    sap: 'SAP',
    sybase: 'Sybase',

    // Certifications
    bs15000: 'BS 15000',
    iso20k: 'ISO 20K',
    cmmiDev: 'CMMI-DEV',
    iso27001: 'ISO 27001 (BS 7799 merged)',
    cmmiSvc: 'CMMI-SVC',
    iso9001: 'ISO 9001 Quality',
    cobit: 'COBIT',
    pcmm: 'PCMM',
    copc2000: 'COPC 2000',
    sixSigma: 'Six Sigma Businesses',
    escm: 'eSCM Establishing',

    // Organizations
    menaInnovation: 'MENA Innovation 2018',
    cit: 'CIT',
    eitisal: 'EITISAL',
    elabs: 'eLABs',
    iti: 'ITI',
    foccit: 'FoCCIT',
    itec: 'ITEC',

    // Partnerships
    microsoftCertifiedPartner: 'Microsoft Certified Partner',
    hpPreferredPartner: 'HP Preferred Partner',
    oracleCertifiedPartner: 'Oracle Certified Partner',
    ibmPartner: 'IBM Partner',
    intelCertifiedPartner: 'Intel Certified Partner',
    ciscoPartner: 'Cisco Partner',

    // Nationalities
    egyptian: 'Egyptian',
    american: 'American',
    british: 'British',
    canadian: 'Canadian',
    french: 'French',
    german: 'German',
    indian: 'Indian',
    italian: 'Italian',
    japanese: 'Japanese',
    mexican: 'Mexican',
    nigerian: 'Nigerian',
    russian: 'Russian',
    southAfrican: 'South African',
    spanish: 'Spanish',
    swedish: 'Swedish',
    turkish: 'Turkish',
    ukrainian: 'Ukrainian',
    vietnamese: 'Vietnamese',
    chinese: 'Chinese',
    brazilian: 'Brazilian',

    // ProfilePage translations
    profileDetails: 'Profile Details',
    editProfile: 'Edit Profile',
    exportPDF: 'Export PDF',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    profileCompletion: 'Profile Completion',
    error: 'Error!',
    errorProcessingProfile: 'There was an error processing your profile.',
    completeIt: 'complete it',
    close: 'Close',
    warning: 'Warning!',
    profileFiftyPercentComplete: 'Your profile is 50% complete.',
    info: 'Info!',
    keepProfileUpdated: 'Keep your profile updated for better opportunities.',
    companyLogo: 'Company Logo',
    dummyCompanyName: 'Dummy Company Name',
    fiscalCapital: 'Fiscal Capital',
    annualRevenue: 'Annual Revenue',
    export: 'Export',
    ownershipNationality: 'Ownership Nationality',
    percentageEgyptianOwnership: 'Percentage Egyptian Ownership',
    percentageNonEgyptianOwnership: 'Percentage Non-Egyptian Ownership',
    partnersNationalities: 'Partners Nationalities',
    totalNumberOfEmployees: 'Total Number of Employees',
    yearOfEstablishment: 'Year of Establishment',
    companySize: 'Company Size',
    typeOfOwnership: 'Type of Ownership',
    companyData: 'Company Data',
    additionalInformation: 'Additional Information',
    keyTechnologies: 'Key Technologies',
    certificates: 'Certificates',
    affiliation: 'Affiliation',
    memberships: 'Memberships',
    partnerships: 'Partnerships',
    contactPersons: 'Contact Persons',
    products: 'Products',
    services: 'Services',
    customerReferences: 'Customer References',
    exportInformation: 'Export Information',
    owners: 'Owners',
    domesticSalesDetails: 'Domestic Sales Details',
    productName: 'Product Name',
    description: 'Description',
    serviceName: 'Service Name',
    customerName: 'Customer Name',
    country: 'Country',
    projectSize: 'Project Size',
    scope: 'Scope',
    industriesSector: 'Industries Sector',
    projectDescription: 'Project Description',
    year: 'Year',
    marketRegion: 'Market Region',
    valueExported: 'Value Exported',
    name: 'Name',
    mobile: 'Mobile',
    telephone: 'Telephone',
    email: 'Email',
    ownerName: 'Name',
    ownerMobile: 'Mobile',
    ownerTelephone: 'Telephone',
    ownerEmail: 'Email',
    domesticSalesYear: 'Year',
    domesticSalesValue: 'Value',
    totalRevenueYear: 'Total Revenue Year',
    email2: 'Email 2',
    mobilePhone: 'Mobile Phone',
    select: 'Select',
    companyInCharge: 'Company in Charge',
    representative: 'Representative',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    enterprise: 'Enterprise',

    // Additional missing translations for ProfilePage sections
    exportInformation: 'Export Information',
    owners: 'Owners',
    domesticSalesDetails: 'Domestic Sales Details',
    additionalInformation: 'Additional Information',
    valueExported: 'Value Exported',
    ownerName: 'Name',
    ownerMobile: 'Mobile',
    ownerTelephone: 'Telephone',
    ownerEmail: 'Email',
    domesticSalesYear: 'Year',
    domesticSalesValue: 'Value',
    totalRevenueYear: 'Total Revenue Year'
  },
  ar: {
    // Header
    home: 'الرئيسية',
    benefits: 'الفوائد',
    contact: 'اتصل بنا',
    callUs: 'اتصل: 16248',

    city: 'المدينة',
    mobilePhone: 'رقم الجوال',

    // Added missing translations for CompanyHeadInformation.tsx
    district: 'الحي',
    street: 'الشارع',
    namePlaceholder: 'اسمك',
    positionPlaceholder: 'المنصب',
    mobilePlaceholder: 'رقم الجوال',
    nationalIdPlaceholder: 'الرقم القومي',
    emailPlaceholder: 'البريد الإلكتروني',
    email2Placeholder: 'البريد الإلكتروني 2',
    websitePlaceholder: 'موقع الويب / منصة التواصل الاجتماعي (لينكدإن، إنستغرام، ..)',
    companyHeadTitle: 'رئيس الشركة',
    submit: 'إرسال',

    // Hero additional
    companies: 'الشركات',
    licenses: 'التراخيص',
    partners: 'الشركاء',

    // LoginForm additional
    accessAccountDesc: 'الوصول إلى حسابك في إيتيدا وإدارة أنشطتك في تكنولوجيا المعلومات والاتصالات',
    enterUsernameEmail: 'أدخل اسم المستخدم أو البريد الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    recoverNow: 'استعادة الآن',

    // Services additional
    itidaServices: 'خدمات إيتيدا',
    services: 'الخدمات',

    // Footer additional
    footerDesc: 'تمكين التحول الرقمي في مصر من خلال تنظيم شامل لقطاع تكنولوجيا المعلومات والاتصالات، دعم الابتكار، وتطوير النظام البيئي.',
    quickLinks: 'روابط سريعة',
    aboutItida: 'حول إيتيدا',
    trainingPrograms: 'برامج التدريب',
    copyright: '© 2024 إيتيدا. جميع الحقوق محفوظة.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    cookiePolicy: 'سياسة ملفات تعريف الارتباط',
    contactLabel: 'التواصل:',
    emailLabel: 'البريد الإلكتروني:',
    addressLabel: 'العنوان (كما هو موضح في السجل التجاري أو بالبطاقة الضريبية)',
    addressText: 'القرية الذكية، طريق الصحراء القاهرة-الإسكندرية، الجيزة، مصر',

    // Registration Sidebar
    registrationCompany: 'تسجيل الشركة',
    companyHeadContacts: 'رئيس الشركة وجهات الاتصال',
    financialInformation: 'المعلومات المالية',

    // Hero
    heroTitle: 'انضم إلى السجل الرسمي لقطاع تكنولوجيا المعلومات في مصر',
    heroSubtitle: 'تمكين الابتكار الرقمي والنمو',
    heroDescription: 'وكالة تنمية صناعة تكنولوجيا المعلومات (إيتيدا) هي السلطة الحكومية المركزية التي تنظم قطاع تكنولوجيا المعلومات والاتصالات في مصر.',
    learnMore: 'اعرف المزيد',

    // Login Form
    alreadyMember: 'عضو إيتيدا بالفعل',
    usernameEmail: 'اسم المستخدم أو البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    login: 'تسجيل الدخول',
    forgotPassword: 'نسيت كلمة المرور؟',
    joinNow: 'انضم إلى إيتيدا الآن',
    dontHaveAccount: 'ليس لديك حساب؟',
    registerHere: 'سجل هنا',
    username: 'إسم المستخدم/البريد الإلكتروني',
    crn: 'CRN',
    licenseNo: 'رقم الترخيص',

    // User Roles
    userRole: 'دور المستخدم',
    individual: 'فرد',
    company: 'شركة',
    government: 'حكومة',

    // Features
    featuresTitle: 'لماذا تختار إيتيدا؟',
    licensing: 'الترخيص',
    licensingDesc: 'تراخيص رسمية للأنشطة المتعلقة بتكنولوجيا المعلومات',
    innovation: 'دعم الابتكار',
    innovationDesc: 'تعزيز الابتكار الرقمي',
    ecosystem: 'النظام البيئي الرقمي',
    ecosystemDesc: 'مجتمع تكنولوجيا المعلومات المزدهر',
    secureAccess: 'بوابة الوصول الآمن',
    secureAccessDesc: 'الوصول إلى لوحة تحكم إيتيدا مع أمان على مستوى المؤسسة',
    recoverYourAccount: 'استعادة حسابك',
    recoverYourAccountDesc: 'استعادة الوصول إلى حسابك في إيتيدا بسهولة من خلال عملية الاستعادة الآمنة',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorAuthDesc: 'أمان محسن لحسابك',
    encryptedComm: 'التواصل المشفر',
    encryptedCommDesc: 'جميع البيانات مشفرة أثناء النقل',
    realTimeMonitoring: 'المراقبة في الوقت الفعلي',
    realTimeMonitoringDesc: 'تتبع أنشطتك وتراخيصك',

    // Features Additional
    comprehensiveIctSolutions: 'حلول تكنولوجيا المعلومات الشاملة',
    comprehensiveIctSolutionsDesc: 'من الترخيص والتنظيم إلى دعم الابتكار وتطوير النظام البيئي، توفر إيتيدا حلولاً شاملة لرحلة التحول الرقمي في مصر.',
    governmentBackedAuthority: 'سلطة مدعومة من الحكومة',
    internationalStandardsCompliance: 'الامتثال للمعايير الدولية',
    support24x7: 'الدعم والمساعدة على مدار 24/7',
    exploreAllServices: 'استكشف جميع الخدمات',
    discoverBenefits: 'اكتشف الفوائد والخدمات الشاملة التي تجعل إيتيدا السلطة الرائدة في تطوير قطاع تكنولوجيا المعلومات في مصر',
    backToHome: 'العودة للرئيسية',

    // Forgot Password
    forgotPasswordTitle: 'نسيت كلمة المرور؟',
    forgotPasswordSubtitle: 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
    emailAddress: 'عنوان البريد الإلكتروني',
    enterEmail: 'أدخل بريدك الإلكتروني',
    sendResetLink: 'إرسال رابط إعادة التعيين',
    sending: 'جاري الإرسال...',
    checkYourEmail: 'تحقق من بريدك الإلكتروني',
    resetInstructions: 'لقد أرسلنا رابط إعادة تعيين كلمة المرور إلى {email}. يرجى التحقق من بريدك الإلكتروني والنقر على الرابط لإعادة تعيين كلمة المرور.',
    backToLogin: 'العودة إلى تسجيل الدخول',
    sendAnotherEmail: 'إرسال بريد إلكتروني آخر',
    didntReceiveEmail: 'لم تستلم البريد الإلكتروني؟ تحقق من مجلد الرسائل غير المرغوب فيها أو اتصل بالدعم.',
    needHelp: 'تحتاج مساعدة؟',
    contactSupport: 'اتصل بالدعم',
    helpCenter: 'مركز المساعدة',
    pleaseEnterEmail: 'يرجى إدخال عنوان البريد الإلكتروني',
    pleaseEnterValidEmail: 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    somethingWentWrong: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',

    // Footer
    poweredBy: 'مدعوم بفخر من إيتيدا',
    itidaDb: 'قاعدة بيانات إيتيدا',

    // Registration Page
    companiesRegistrationForm: 'نموذج تسجيل الشركات',
    completeCompanyRegistration: 'أكمل تسجيل شركتك مع إيتيدا',
    companyLegalInformation: 'البيانات القانونية للشركة',
    contactInformation: 'معلومات الاتصال',
    activitiesAttachments: 'الأنشطة والمرفقات',
    previous: 'السابق',
    next: 'التالي',
    submitRegistration: 'إرسال التسجيل',
    companyOverView: 'نظرة عامة على الشركة',
    companyOverviewPlaceholder: 'وصف باختصار خلفية شركتك وكفاءاتها الأساسية وإنجازاتها الرئيسية.',

    // Tab 1: Company Legal Information
    companyLegalInfoTitle: 'البيانات القانونية للشركة',
    companyLegalInfoSubtitle: '(كما هو مذكور بالسجل التجاري أو بالبطاقة الضريبية)',
    companyNameEnglish: 'إسم المنشأة الإنجليزي كما هو مذكور بالسجل التجاري',
    companyNameArabic: 'إسم المنشأة العربي كما هو مذكور بالسجل التجاري',
    commercialDenomination: 'السمة التجارية',
    legalType: 'الشكل القانوني للمنشأة',
    selectLegalType: 'اختر الشكل القانوني',
    soleProprietorship: 'منشأة فردية',
    partnership: 'شركة تضامن',
    limitedLiabilityCompany: 'شركة ذات مسؤولية محدودة',
    jointStockCompany: 'شركة مساهمة',
    branch: 'فرع',
    other: 'أخرى',
    registerUsing: 'التسجيل باستخدام',
    commercialRegistryNumber: 'رقم السجل التجاري',
    unifiedCommercialRegistryNumber: 'رقم السجل التجاري الموحد',
    taxRegistryNumber: 'رقم التسجيل الضريبي',
    commercialRegistrationDate: 'تاريخ اصدار السجل',
    noteRegistrationOptions: 'ملاحظة: يجب أن يكون أحد خيارات التسجيل محددا على الأقل',
    officialCompanyEmail: 'البريد الإلكتروني الرسمي للشركة',
    yearOfEstablishment: 'سنة التأسيس',
    selectYear: 'اختر السنة',
    companyClassification: 'تصنيف الشركة',
    crOffice: 'مكتب السجل التجاري',
    classCode: 'كود الفئة',
    classCodeArabic: 'كود الفئة',
    mainBranch: 'محل رئيسى',
    otherMain: 'رئيسى آخر',
    branchOffice: 'محل فرعى',
    branchOther: 'فرعى',
    generalCenter: 'مركز عام',

    // Validation Messages
    thisFieldIsRequired: 'هذا الحقل مطلوب',
    onlyEnglishLettersAllowed: 'يسمح بالحروف الإنجليزية فقط',
    onlyArabicLettersAllowed: 'يسمح بالحروف العربية فقط',
    invalidEmailAddress: 'عنوان بريد إلكتروني غير صحيح',
    atLeastOneCompanyClassificationRequired: 'يجب اختيار تصنيف شركة واحد على الأقل',
    atLeastOneRegistrationMethodSelected: 'يجب اختيار طريقة تسجيل واحدة على الأقل',
    commercialRegistryNumberRequired: 'رقم السجل التجاري مطلوب',
    unifiedCommercialRegistryNumberRequired: 'رقم السجل التجاري الموحد مطلوب',
    taxRegistryNumberRequired: 'رقم التسجيل الضريبي مطلوب',

    // Alert Messages
    alertTitle: 'خطأ في التحقق',
    alertTitleSuccess: 'نجح',
    alertTitleWarning: 'تحذير',
    alertTitleError: 'خطأ',
    pleaseCompleteAllRequiredFields: 'يرجى إكمال جميع الحقول المطلوبة قبل المتابعة',
    pleaseCompleteEmptyFields: 'يرجى إكمال الحقول الفارغة التالية:',
    formSubmissionBlocked: 'تم منع إرسال النموذج بسبب عدم اكتمال الحقول المطلوبة',
    pleaseFillRequiredInformation: 'يرجى ملء جميع المعلومات المطلوبة للمتابعة',
    missingRequiredData: 'بيانات مطلوبة مفقودة',
    incompleteFormData: 'بيانات النموذج غير مكتملة',
    validationFailed: 'فشل التحقق',
    pleaseCheckFormData: 'يرجى مراجعة بيانات النموذج والمحاولة مرة أخرى',
    requiredFieldsEmpty: 'بعض الحقول المطلوبة فارغة',
    pleaseCompleteForm: 'يرجى إكمال النموذج قبل الإرسال',
    dataValidationError: 'خطأ في التحقق من البيانات',
    formNotComplete: 'النموذج غير مكتمل',
    pleaseReviewForm: 'يرجى مراجعة وإكمال النموذج',

    // Company Classification Options
    technology: 'تكنولوجيا',
    consulting: 'استشارات',
    manufacturing: 'تصنيع',
    retail: 'تجزئة',
    finance: 'مالية',
    healthcare: 'رعاية صحية',
    education: 'تعليم',

    // Class Code Options
    selectClassCode: 'اختر كود الفئة',

    // Legal Type Options
    legalTypeSole: 'Sole proprietorship Co - شركة شخص واحد',
    legalTypeSoleCorporation: 'Sole Corporation - فردي',
    legalTypeGeneralPartnership: 'General Partnership - شركات مساهمة',
    legalTypeLimitedLiability: 'Limited Liability Company - ذات مسئولية محدودة',
    legalTypeJoint: 'Joint - شركة تضامن',
    legalTypeSpecialLimited: 'Special Limited Partnership – توصية بسيطة',
    legalTypeInherited: 'Inherited Company - واقع موروثة',
    legalTypeLimitedShares: 'Limited Partnership by Shares - توصية بالاسهم',
    legalTypeCooperative: 'Cooperative Associations - جمعيات تعاونية',
    legalTypeDeFacto: 'De Facto Company - شركه واقع',
    legalTypeBranchForeign: 'Branch of Foreign Company - فرع شركه اجنبيه',
    legalTypeNonProfit: 'Non-Profit Entities - جهات غير هادفة',

    // Tab 2: Contact Information
    contactInfoTitle: 'معلومات الاتصال',
    contactInfoSubtitle: 'معلومات الاتصال والمدير المسئول',
    companyAddress: 'عنوان الشركة',
    governorate: 'المحافظة',
    selectGovernorate: 'اختر المحافظة',
    districtCity: 'الحي - المدينة',
    streetAddress: 'العنوان',
    companyContactInfo: 'معلومات الاتصال بالشركة',
    companyWebsiteUrl: 'موقع الشركة الإلكتروني',
    officialEmail: 'البريد الإلكتروني الرسمي',
    phoneMobile: 'رقم الموبايل',
    companyHasBranches: 'نعم، للشركة فروع',
    companyRepresentative: 'بيانات المدير المسئول و مقدم الطلب',
    representativeSubtitle: '(كما هو موضح بالسجل التجاري أو توكيل الإدارة)',
    name: 'الإسم',
    title: 'الصفة',
    mobile: 'رقم المحمول',
    nationalId: 'الرقم القومي',
    email: 'البريد الإلكتروني',
    requestApplicant: 'مقدم الطلب',
    companyInCharge: 'المدير المسئول كما هو موضح بالسجل التجارية أو توكيل بالإدارة',
    representative: 'مفوض',
    noteRequiredFields: 'ملاحظة: جميع الحقول المطلوبة يجب ملؤها قبل الانتقال للخطوة التالية',
    dateIsRequired: 'التاريخ مطلوب',
    invalidFormatUseMMYYYY: 'تنسيق غير صحيح. استخدم MM/YYYY',
    yearMustBeAtLeast15YearsAgo: 'يجب أن يكون العام قبل 15 عامًا على الأقل (قبل {year})',
    companyHead: 'رئيس الشركة',
    nidIssuedFrom: 'صادر من',
    egCairo: 'مثال: القاهرة',
    nidIssueDate: 'تاريخ إصدار الرقم القومي',
    mmYYYY: 'MM/YYYY',
    representativeInformations: 'معلومات الممثل',
    nationalIdRequired: 'الرقم القومي مطلوب',
    nationalId14Digits: 'يجب أن يكون الرقم القومي 14 رقمًا بالضبط',
    dateRangeError: 'يجب أن يكون التاريخ بين {minDate} واليوم',
    exampleGovernorate: 'مثال: القاهرة',
    dateFormat: 'MM/YYYY',

    // Job Titles
    jobTitleResponsibleManager: 'مدير مسئول',
    jobTitlePartner: 'شريك',
    jobTitleManagerAndPartner: 'مدير و شريك',

    // Governorates
    cairo: 'القاهرة',
    giza: 'الجيزة',
    alexandria: 'الإسكندرية',
    sharqia: 'الشرقية',
    gharbia: 'الغربية',
    menoufia: 'المنوفية',
    qalyubia: 'القليوبية',
    portSaid: 'بورسعيد',
    suez: 'السويس',
    ismailia: 'الإسماعيلية',
    kafrElSheikh: 'كفر الشيخ',
    beheira: 'البحيرة',
    assiut: 'أسيوط',
    sohag: 'سوهاج',
    qena: 'قنا',
    luxor: 'الأقصر',
    aswan: 'أسوان',
    redSea: 'البحر الأحمر',
    newValley: 'الوادي الجديد',
    matruh: 'مطروح',
    northSinai: 'شمال سيناء',
    southSinai: 'جنوب سيناء',
    beniSuef: 'بني سويف',
    fayoum: 'الفيوم',
    minya: 'المنيا',
    dakahlia: 'الدقهلية',
    damietta: 'دمياط',
    otherGovernorate: 'أخرى',

    // Tab 3: Company Branches
    companyBranchesTitle: 'فروع الشركة',
    companyBranchesSubtitle: 'إدارة معلومات فروع الشركة',
    hasBranches: 'للشركة فروع',
    branchName: 'اسم الفرع',
    branchLocation: 'موقع الفرع',
    branchCountry: 'دولة الفرع',
    branchGovernorate: 'محافظة الفرع',
    branchCity: 'مدينة الفرع',
    branchDistrict: 'حي الفرع',
    branchEmail: 'بريد الفرع الإلكتروني',
    enterBranchName: 'أدخل اسم الفرع',
    enterBranchLocation: 'أدخل موقع الفرع',
    enterBranchCountry: 'أدخل دولة الفرع',
    enterBranchGovernorate: 'أدخل محافظة الفرع',
    enterBranchCity: 'أدخل مدينة الفرع',
    enterBranchDistrict: 'أدخل حي الفرع',
    enterBranchEmail: 'أدخل بريد الفرع الإلكتروني',
    addBranchInfo: 'أضف معلومات فروع شركتك هنا.',
    branchNumber: 'فرع',
    removeBranch: 'حذف الفرع',
    addBranch: 'إضافة فرع',

    // Tab 4: Activities & Attachments
    activitiesAttachmentsTitle: 'الأنشطة والمرفقات',
    activitiesAttachmentsSubtitle: 'اختر الأنشطة المطلوبة وارفق المستندات المطلوبة',
    activitiesRequiredForLicensing: 'الأنشطة المطلوب الترخيص بمزاولتها',
    softwareDesignServices: 'خدمات تصميم وإنتاج وتطوير البرمجيات',
    itSystemsServices: 'خدمات تصميم وتطوير وإنتاج وتوريد وتشغيل أنظمة تكنولوجيا المعلومات',
    trustServices: 'خدمات الثقة والتوقيع الإلكتروني',
    websitesPlatformsServices: 'خدمات المواقع والمنصات والمعاملات الإلكترونية باستخدام شبكة الإنترنت',
    electronicsEmbeddedServices: 'خدمات تصميم وتطوير الإلكترونيات والأنظمة المدمجة، وإنتاج الإلكترونيات في مجال تكنولوجيا المعلومات والاتصالات',
    contentDigitizationServices: 'خدمات رقمنة المحتوى التقليدي باستخدام تكنولوجيا المعلومات',
    callCenterBusinessServices: 'خدمات مراكز الاتصال وإدارة الأعمال باستخدام تكنولوجيا المعلومات والاتصالات',
    consultingResearchServices: 'خدمات الاستشارات والبحوث والتطوير وريادة الأعمال في مجال تكنولوجيا المعلومات والاتصالات',
    trainingLearningServices: 'خدمات التدريب والتعلم في مجال تكنولوجيا المعلومات والاتصالات',
    attachments: 'المرفقات',
    attachmentsNote: 'ملاحظة: يتم قبول الصور وملفات PDF فقط بحد أقصى 3 ميجابايت',
    commercialRegisterImage: 'صورة السجل التجاري أو قرار الإشهار',
    taxCardImage: 'صورة البطاقة الضريبية',
    nationalIdImage: 'صورة إثبات الشخصية (الرقم القومي) للمدير المسئول',
    investmentGazetteImage: 'صورة صحيفة الإستثمار أو الشركات أو عقد الشركة',
    declarationUndertakingImage: 'إقرار وتعهد بشأن مزاولة أنشطة تكنولوجيا المعلومات',
    representativeAuthorizationImage: 'ملف تفويض الممثل',
    representativeNationalIdImage: 'الرقم القومي للممثل',
    licenseReceipt: 'إستلام الترخيص',
    methodOfLicenseReceipt: 'طريقة إستلام الترخيص',
    selectReceiptMethod: 'اختر طريقة الاستلام',
    postalMail: 'بريد عادي',
    personalPickup: 'استلام شخصي',
    courier: 'ساعي',
    declarationAgreement: 'الإقرار والموافقة',
    declarationText: 'أقر وأتعهد بصحة المستندات المقدمة والتزامي بالقوانين المصرية ذات الصلة، بما في ذلك قوانين التوقيع الإلكتروني وحقوق الملكية الفكرية وحماية البيانات الشخصية ومكافحة الجرائم الإلكترونية. كما أتعهد بمزاولة الأنشطة المرخصة بأمان وأخلاقيات ومسؤولية وشفافية.',
    iAgree: 'أوافق',
    noteDeclarationAgreement: 'ملاحظة: يجب الموافقة على الإقرار والموافقة قبل إرسال الطلب',

    // Additional Benefits
    additionalBenefitsTitle: 'تنظيم تراخيص أنشطة تكنولوجيا المعلومات',
    additionalBenefitsDesc: 'تصدر وكالة تنمية صناعة تكنولوجيا المعلومات (إيتيدا) تراخيص لممارسة الأنشطة المتخصصة في قطاع تكنولوجيا المعلومات والاتصالات لتنظيم قطاع تكنولوجيا المعلومات وتشجيع الاستثمار في هذا المجال الحيوي. تهدف هذه المبادرة إلى دعم نمو السوق وتعزيز بيئة أعمال رقمية حيوية.',
    activitiesEligible: 'الأنشطة المؤهلة للترخيص:',
    eligibleActivities: [
      'خدمات تصميم وإنتاج وتطوير البرمجيات.',
      'خدمات تصميم وتطوير وإنتاج وتوريد وتشغيل أنظمة تكنولوجيا المعلومات.',
      'خدمات المواقع والمنصات والمعاملات الإلكترونية باستخدام الإنترنت.',
      'تصميم وتطوير الإلكترونيات والأنظمة المدمجة، وتصنيع الإلكترونيات في مجال تكنولوجيا المعلومات والاتصالات.',
      'خدمات رقمنة المحتوى التقليدي باستخدام تكنولوجيا المعلومات.',
      'خدمات مراكز الاتصال وإدارة العمليات التجارية باستخدام تكنولوجيا المعلومات والاتصالات.',
      'خدمات الاستشارات والبحوث والتطوير وريادة الأعمال في تكنولوجيا المعلومات والاتصالات.',
      'خدمات التدريب والتعليم في تكنولوجيا المعلومات والاتصالات.'
    ],

    // Financial Information - Missing translations
    chooseFile: 'اختر ملف',
    noFileChosen: 'لم يتم اختيار ملف',
    paidCapital: 'رأس المال المدفوع',
    enterPaidCapital: 'أدخل رأس المال المدفوع',
    companySubClassification: 'التصنيف الفرعي للشركة',
    industrySectors: 'قطاعات الصناعة',
    selected100PercentEgyptian: 'المحدد (100% مصري)',
    enterDomesticSalesYear: 'أدخل سنة المبيعات المحلية',
    enterDomesticSalesValue: 'أدخل قيمة المبيعات المحلية',
    enterTotalRevenueYear: 'أدخل سنة إجمالي الإيرادات',
    enterAnnualRevenue: 'أدخل الإيرادات السنوية',
    enterTotalNumberOfEmployees: 'أدخل إجمالي عدد الموظفين',
    selectCompanySize: 'اختر حجم الشركة',
    selectKeyTechnologies: 'اختر التقنيات الرئيسية',
    enterCustomKeyTechnology: 'أدخل تقنية رئيسية مخصصة',
    selectAffiliations: 'اختر الانتماءات',
    enterCustomAffiliation: 'أدخل انتماء مخصص',
    selectMemberships: 'اختر العضويات',
    enterCustomMembership: 'أدخل عضوية مخصصة',
    selectCertificates: 'اختر الشهادات',
    enterCustomCertificate: 'أدخل شهادة مخصصة',
    selectPartnerships: 'اختر الشراكات',
    enterCustomPartnership: 'أدخل شراكة مخصصة',
    products: 'المنتجات',
    productName: 'اسم المنتج',
    productDescription: 'وصف المنتج',
    services: 'الخدمات',
    serviceName: 'اسم الخدمة',
    serviceDescription: 'وصف الخدمة',
    customerReference: 'مرجع العميل',
    customerName: 'اسم العميل',
    selectCountry: 'اختر البلد',
    projectSize: 'حجم المشروع',
    scope: 'النطاق',
    industriesSector: 'قطاع الصناعات',
    projectDescription: 'وصف المشروع',
    companyClassifications: 'تصنيفات الشركة',
    selectCompanyClassification: 'اختر تصنيف الشركة',
    selectSubClassification: 'اختر التصنيف الفرعي',
    selectIndustrySector: 'اختر قطاع الصناعة',
    year: 'السنة',
    marketRegion: 'منطقة السوق',
    country: 'البلد',
    typesProductsServicesExported: 'أنواع المنتجات / الخدمات المصدرة',
    totalAmountExportsYearUSD: 'إجمالي مبلغ الصادرات / السنة بالدولار الأمريكي',
    percentageOfEgyptianOwnership: 'نسبة الملكية المصرية',
    percentageOfNonEgyptianOwnership: 'نسبة الملكية غير المصرية',
    selectNationality: 'اختر الجنسية',
    yes: 'نعم',
    no: 'لا',
    exportInformation: 'معلومات التصدير',
    smallEmployees: 'صغيرة (1-10 موظفين)',
    mediumEmployees: 'متوسطة (11-50 موظف)',
    largeEmployees: 'كبيرة (51-200 موظف)',
    enterpriseEmployees: 'مؤسسة (200+ موظف)',
    selectCountryPlaceholder: 'اختر البلد',
    itidaLogoAlt: 'شعار إيتيدا',
    englishFlagAlt: 'الإنجليزية',
    arabicFlagAlt: 'العربية',
    switchToArabic: 'التبديل إلى العربية',
    switchToEnglish: 'التبديل إلى الإنجليزية',

    // Financial Information - Additional missing translations
    auditedBalanceSheet: 'الميزانية العمومية المدققة/قائمة الدخل/الإقرار الضريبي + شهادة المحاسب القانوني',
    domesticSalesDetails: 'تفاصيل المبيعات المحلية',
    domesticSalesYear: 'سنة المبيعات المحلية',
    domesticSalesValue: 'قيمة المبيعات المحلية',
    totalRevenueYear: 'سنة إجمالي الإيرادات',
    annualRevenue: 'الإيرادات السنوية',
    totalNoOfEmployees: 'إجمالي عدد الموظفين',
    companySize: 'حجم الشركة',
    keyTechnologies: 'التقنيات الرئيسية',
    affiliation: 'الانتماء',
    memberships: 'العضويات',
    certificates: 'الشهادات',
    partnerships: 'الشراكات',
    products: 'المنتجات',
    services: 'الخدمات',
    customerReference: 'مرجع العميل',
    companyClassifications: 'تصنيفات الشركة',
    exportInformation: 'معلومات التصدير',
    marketRegion: 'منطقة السوق',
    typesProductsServicesExported: 'أنواع المنتجات / الخدمات المصدرة',
    totalAmountExportsYearUSD: 'إجمالي مبلغ الصادرات / السنة بالدولار الأمريكي',
    percentageOfEgyptianOwnership: 'نسبة الملكية المصرية',
    percentageOfNonEgyptianOwnership: 'نسبة الملكية غير المصرية',
    partnersOrShareholdersNationalities: 'جنسيات الشركاء أو المساهمين',
    companyHasBranches: 'للشركة فروع',
    export: 'تصدير',
    import: 'استيراد',
    ownership: 'الملكية',
    nationality: 'الجنسية',
    others: 'أخرى',
    manufacturing: 'تصنيع',
    retail: 'تجزئة',
    consulting: 'استشارات',
    technology: 'تكنولوجيا',
    finance: 'مالية',
    healthcare: 'رعاية صحية',
    education: 'تعليم',
    government: 'حكومة',
    nonProfit: 'غير هادفة للربح',
    other: 'أخرى',
    production: 'إنتاج',
    assembly: 'تجميع',
    outsourcing: 'الاستعانة بمصادر خارجية',
    ecommerce: 'التجارة الإلكترونية',
    physicalStores: 'المتاجر الفعلية',
    b2b: 'B2B',
    b2c: 'B2C',
    it: 'تكنولوجيا المعلومات',
    doYouExport: 'هل تقوم بالتصدير',
    marketInformation: 'معلومات السوق',
    softwareDevelopment: 'تطوير البرمجيات',
    hardware: 'الأجهزة',

    // Technology Companies
    ibm: 'آي بي إم',
    microsoft: 'مايكروسوفت',
    oracle: 'أوراكل',
    sun: 'سان',
    java: 'جافا',
    openSource: 'مفتوح المصدر',
    sap: 'ساب',
    sybase: 'سايبيس',

    // Certifications
    bs15000: 'BS 15000',
    iso20k: 'ISO 20K',
    cmmiDev: 'CMMI-DEV',
    iso27001: 'ISO 27001 (BS 7799 merged)',
    cmmiSvc: 'CMMI-SVC',
    iso9001: 'ISO 9001 Quality',
    cobit: 'COBIT',
    pcmm: 'PCMM',
    copc2000: 'COPC 2000',
    sixSigma: 'Six Sigma Businesses',
    escm: 'eSCM Establishing',

    // Organizations
    menaInnovation: 'MENA Innovation 2018',
    cit: 'CIT',
    eitisal: 'EITISAL',
    elabs: 'eLABs',
    iti: 'ITI',
    foccit: 'FoCCIT',
    itec: 'ITEC',

    // Partnerships
    microsoftCertifiedPartner: 'Microsoft Certified Partner',
    hpPreferredPartner: 'HP Preferred Partner',
    oracleCertifiedPartner: 'Oracle Certified Partner',
    ibmPartner: 'IBM Partner',
    intelCertifiedPartner: 'Intel Certified Partner',
    ciscoPartner: 'Cisco Partner',

    // Nationalities
    egyptian: 'مصري',
    american: 'أمريكي',
    british: 'بريطاني',
    canadian: 'كندي',
    french: 'فرنسي',
    german: 'ألماني',
    indian: 'هندي',
    italian: 'إيطالي',
    japanese: 'ياباني',
    mexican: 'مكسيكي',
    nigerian: 'نيجيري',
    russian: 'روسي',
    southAfrican: 'جنوب أفريقي',
    spanish: 'إسباني',
    swedish: 'سويدي',
    turkish: 'تركي',
    ukrainian: 'أوكراني',
    vietnamese: 'فيتنامي',
    chinese: 'صيني',
    brazilian: 'برازيلي',

    // ProfilePage translations
    profileDetails: 'تفاصيل الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    exportPDF: 'تصدير PDF',
    cancel: 'إلغاء',
    saveChanges: 'حفظ التغييرات',
    profileCompletion: 'إكمال الملف الشخصي',
    error: 'خطأ!',
    errorProcessingProfile: 'حدث خطأ في معالجة ملفك الشخصي.',
    completeIt: 'أكمله',
    close: 'إغلاق',
    warning: 'تحذير!',
    profileFiftyPercentComplete: 'ملفك الشخصي مكتمل بنسبة 50%.',
    info: 'معلومات!',
    keepProfileUpdated: 'حافظ على تحديث ملفك الشخصي للحصول على فرص أفضل.',
    companyLogo: 'شعار الشركة',
    dummyCompanyName: 'اسم الشركة الوهمي',
    fiscalCapital: 'رأس المال المالي',
    annualRevenue: 'الإيرادات السنوية',
    export: 'تصدير',
    ownershipNationality: 'جنسية الملكية',
    percentageEgyptianOwnership: 'نسبة الملكية المصرية',
    percentageNonEgyptianOwnership: 'نسبة الملكية غير المصرية',
    partnersNationalities: 'جنسيات الشركاء',
    totalNumberOfEmployees: 'إجمالي عدد الموظفين',
    yearOfEstablishment: 'سنة التأسيس',
    companySize: 'حجم الشركة',
    typeOfOwnership: 'نوع الملكية',
    companyData: 'بيانات الشركة',
    additionalInformation: 'معلومات إضافية',
    keyTechnologies: 'التقنيات الرئيسية',
    certificates: 'الشهادات',
    affiliation: 'الانتماء',
    memberships: 'العضويات',
    partnerships: 'الشراكات',
    contactPersons: 'أشخاص الاتصال',
    products: 'المنتجات',
    services: 'الخدمات',
    customerReferences: 'مراجع العملاء',
    exportInformation: 'معلومات التصدير',
    owners: 'الملاك',
    domesticSalesDetails: 'تفاصيل المبيعات المحلية',
    productName: 'اسم المنتج',
    description: 'الوصف',
    serviceName: 'اسم الخدمة',
    customerName: 'اسم العميل',
    country: 'البلد',
    projectSize: 'حجم المشروع',
    scope: 'النطاق',
    industriesSector: 'قطاع الصناعات',
    projectDescription: 'وصف المشروع',
    year: 'السنة',
    marketRegion: 'منطقة السوق',
    valueExported: 'القيمة المصدرة',
    name: 'الاسم',
    mobile: 'الموبايل',
    telephone: 'الهاتف',
    email: 'البريد الإلكتروني',
    ownerName: 'الاسم',
    ownerMobile: 'الموبايل',
    ownerTelephone: 'الهاتف',
    ownerEmail: 'البريد الإلكتروني',
    domesticSalesYear: 'السنة',
    domesticSalesValue: 'القيمة',
    totalRevenueYear: 'سنة إجمالي الإيرادات',
    email2: 'البريد الإلكتروني 2',
    mobilePhone: 'رقم الجوال',
    select: 'اختر',
    companyInCharge: 'المدير المسؤول',
    representative: 'الممثل',
    small: 'صغيرة',
    medium: 'متوسطة',
    large: 'كبيرة',
    enterprise: 'مؤسسة',

    // Additional missing translations for ProfilePage sections
    exportInformation: 'معلومات التصدير',
    owners: 'الملاك',
    domesticSalesDetails: 'تفاصيل المبيعات المحلية',
    additionalInformation: 'معلومات إضافية',
    valueExported: 'القيمة المصدرة',
    ownerName: 'الاسم',
    ownerMobile: 'الموبايل',
    ownerTelephone: 'الهاتف',
    ownerEmail: 'البريد الإلكتروني',
    domesticSalesYear: 'السنة',
    domesticSalesValue: 'القيمة',
    totalRevenueYear: 'سنة إجمالي الإيرادات'
  }
}
